framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                    delay: 5000
            failed: 'doctrine://default'
            sync: 'sync://'

        routing:
            App\Foundation\Queue\Message\ServiceMethodMessage: async
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Symfony\Component\Notifier\Message\ChatMessage: async
            # Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async

when@dev:
    framework:
        messenger:
            routing:
                App\Foundation\Queue\Message\ServiceMethodMessage: async
